---
hide_body: false
is_partial: false
fields:
- type: number
  config:
    step: ".01"
    required: true
  label: Price
  name: price
- type: textarea
  name: shortDescription
  label: Short Description
  description: Shows on product and cart pages
- type: file
  name: image
  label: Image
  description: Displays on product page
- type: file
  name: cartImage
  label: Cart Image
  description: Upload a 50x50 image to display in shopping cart
- type: blocks
  name: customOptions
  label: Custom Options
  template_types:
  - text-option
  - text-block-option
  - checkbox-option
  - simple-dropdown-option
  - advanced-dropdown-option
